[exercise]
name = "hashing_basics"
category = "21_crypto"
difficulty = 2
estimated_time = "12m"
go_version = "1.16+"

[description]
title = "Cryptographic Hashing"
summary = "Learn to use cryptographic hash functions for data integrity"
learning_objectives = [
  "Use MD5, SHA1, SHA256, and SHA512 hash functions",
  "Hash data incrementally for large files",
  "Verify data integrity with hash comparison",
  "Understand hash function security properties"
]

[validation]
mode = "run"
timeout = "30s"

[hints]
level_1 = "Hash creation: hasher := sha256.New(); hasher.Write(data)"
level_2 = "Convenience: sha256.Sum256([]byte(data))"
level_3 = "Compare hashes: hash1 == hash2 (for arrays)"

[metadata]
tags = ["crypto", "hashing", "security", "integrity"]
related_exercises = ["21_crypto/encryption_aes.go"]